---
title: Better Contrasts for Ordinal Variables in R
author: Aaron Gullickson
date: '2020-09-11'
slug: better-contrasts-for-ordinal-variables-in-r
categories: []
tags:
  - R
subtitle: 'Use stairstep contrasts, tell a friend'
summary: ''
authors: []
lastmod: '2020-09-11T14:07:36-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>
<link href="/rmarkdown-libs/font-awesome/css/fontawesome-all.min.css" rel="stylesheet" />


<p>Social scientists routinely use categorical variables in linear models. In order to do so, we must code these categorical variables into numeric quantities in some fashion. By far the most common method is the dummy/indicator variable approach. In this approach, we create 0/1 variables for each category where 1 indicates membership in the category. We leave out this coding for one category which becomes the reference category. The estimate for each parameter then gives the mean difference between the indicated category and the reference category, all else being equal. This approach is so ubiquitous that many researchers are probably unaware of the many alternatives that exist for how to code categorical variables. Here I want to highlight an alternative method in R for the case of ordinal variables that can be used to produce much more intuitive results.</p>
<p>To illustrate, I will use <a href="https://github.com/AaronGullickson/combined_stats/tree/master/example_datasets/earnings">data on hourly wages from the Current Population Survey in 2018</a> that I use for my classes. Here is an excerpt of that data.</p>
<pre class="r"><code>load(url(&quot;https://github.com/AaronGullickson/combined_stats/blob/master/example_datasets/earnings/earnings.RData?raw=true&quot;))
head(earnings[,1:6])</code></pre>
<pre><code>##   wages age gender  race            marstat        education
## 1 20.84  52 Female Black Divorced/Separated       HS Diploma
## 2 10.00  19 Female Black      Never Married       HS Diploma
## 3 25.00  56 Female Black Divorced/Separated Bachelors Degree
## 4  9.50  22 Female Black      Never Married       HS Diploma
## 5 17.00  48   Male White      Never Married       HS Diploma
## 6 20.00  59   Male Black      Never Married       HS Diploma</code></pre>
<p>Lets say I want to examine the relationship between hourly wages and education. I could do this by just looking at the mean wages for each educational group. I like to use <code>tapply</code> for these sorts of operations.</p>
<pre class="r"><code>wage_means &lt;- tapply(earnings$wages, earnings$education, mean)
knitr::kable(round(wage_means, 2), col.names=&quot;mean wages&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">mean wages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No HS Diploma</td>
<td align="right">14.26</td>
</tr>
<tr class="even">
<td>HS Diploma</td>
<td align="right">18.67</td>
</tr>
<tr class="odd">
<td>AA Degree</td>
<td align="right">21.91</td>
</tr>
<tr class="even">
<td>Bachelors Degree</td>
<td align="right">30.76</td>
</tr>
<tr class="odd">
<td>Graduate Degree</td>
<td align="right">38.17</td>
</tr>
</tbody>
</table>
<p>Alternatively, I could use a linear model structure to get the same information.</p>
<pre class="r"><code>model_dummy &lt;- lm(wages~education, data=earnings)
knitr::kable(round(coef(model_dummy), 2), col.names=&quot;coefficients&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">14.26</td>
</tr>
<tr class="even">
<td>educationHS Diploma</td>
<td align="right">4.41</td>
</tr>
<tr class="odd">
<td>educationAA Degree</td>
<td align="right">7.65</td>
</tr>
<tr class="even">
<td>educationBachelors Degree</td>
<td align="right">16.50</td>
</tr>
<tr class="odd">
<td>educationGraduate Degree</td>
<td align="right">23.91</td>
</tr>
</tbody>
</table>
<p>Because education is coded as a factor variable, the <code>lm</code> command knows what to do with it. It has created four separate dummy variables, leaving out the no high school diploma group as my reference. As a result, the intercept is the mean wages for the no high school diploma group, and all of the other numbers give me the difference in mean wages of the given educational group relative to the no high school diploma group. I can see, for example, that individuals with a bachelor’s degree make $16.50/hour more on average than those with no high school diploma. I can easily confirm this by looking back to the means I just calculated:</p>
<pre class="r"><code>round(wage_means[2:5]-wage_means[1], 2)</code></pre>
<pre><code>##       HS Diploma        AA Degree Bachelors Degree  Graduate Degree 
##             4.41             7.65            16.50            23.91</code></pre>
<div id="how-did-r-know-what-to-do-with-the-factor-variable" class="section level2">
<h2>How did R know what to do with the factor variable?</h2>
<p>Underneath the surface, every factor variable in <em>R</em> comes with a a matrix of <em>contrasts</em>. This contrast matrix defines how such a factor variable should be converted into a set of variables for a linear model. You can see this contrast matrix with the <code>contrasts</code> command:</p>
<pre class="r"><code>contrasts(earnings$education)</code></pre>
<pre><code>##                  HS Diploma AA Degree Bachelors Degree Graduate Degree
## No HS Diploma             0         0                0               0
## HS Diploma                1         0                0               0
## AA Degree                 0         1                0               0
## Bachelors Degree          0         0                1               0
## Graduate Degree           0         0                0               1</code></pre>
<p>The rows are the categories (or “levels” in R speak) of the factor variable and the columns are the variables that actually enter into the model. The matrix gives the numeric coding of these variables for each category. As you can see, the contrasts here just define a standard dummy/indicator variable coding. The no high school diploma category is my reference and has zero on all four variables. All of the other categories have a one for the relevant variable and a zero otherwise.</p>
<p>When you create a factor variable, R will default to this dummy coding which in R is often called a <em>treatment contrast</em>. But, treatment contrasts are not the only contrasts available and you can create your own contrast as I will show below.</p>
<p>To illustrate a change in contrast, I will change my regular factor variable to an ordered factor. The <code>factor</code> command has the option to make any factor ordered and thus recognize its underlying ordinal structure. I can do this very simply:</p>
<pre class="r"><code>earnings$educ_ordered &lt;- factor(earnings$education, ordered=TRUE)</code></pre>
<p>An ordered factor behaves very similarly to a regular factor but has one major advantage. I can now use greater than and less than operators on my factor in a logical way. For example, lets say I wanted to look at the mean difference in wages between all those with only a high school diploma or less and those with more schooling. Rather than code a whole new variable for this binary comparison, I can just:</p>
<pre class="r"><code>model_binary &lt;- lm(wages~I(educ_ordered&gt;&quot;HS Diploma&quot;), data=earnings)
knitr::kable(round(coef(model_binary), 2), col.names = &quot;coefficients&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">18.10</td>
</tr>
<tr class="even">
<td>I(educ_ordered &gt; “HS Diploma”)TRUE</td>
<td align="right">12.62</td>
</tr>
</tbody>
</table>
<p>Being able to use these operators can be a real time saver if you have an ordinal variable with many categories because you can easily collapse categories for a variety of purposes.</p>
<p>However, ordered factors come with one very annoying “feature” in R. Lets say I want to estimate the same linear model as before but now using my ordered factor. Lets try it out:</p>
<pre class="r"><code>model_ordinal1 &lt;- lm(wages~educ_ordered, data=earnings)
knitr::kable(round(coef(model_ordinal1), 2), col.names=&quot;coefficients&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">24.75</td>
</tr>
<tr class="even">
<td>educ_ordered.L</td>
<td align="right">18.94</td>
</tr>
<tr class="odd">
<td>educ_ordered.Q</td>
<td align="right">3.10</td>
</tr>
<tr class="even">
<td>educ_ordered.C</td>
<td align="right">-0.09</td>
</tr>
<tr class="odd">
<td>educ_ordered^4</td>
<td align="right">-1.65</td>
</tr>
</tbody>
</table>
<p>😮 WTF? What are all of these terms? They certainly are not what I was expecting. We can learn more by looking at the contrasts.</p>
<pre class="r"><code>contrasts(earnings$educ_ordered)</code></pre>
<pre><code>##              .L         .Q            .C         ^4
## [1,] -0.6324555  0.5345225 -3.162278e-01  0.1195229
## [2,] -0.3162278 -0.2672612  6.324555e-01 -0.4780914
## [3,]  0.0000000 -0.5345225 -4.095972e-16  0.7171372
## [4,]  0.3162278 -0.2672612 -6.324555e-01 -0.4780914
## [5,]  0.6324555  0.5345225  3.162278e-01  0.1195229</code></pre>
<p>We are definitely not using dummy coding here! The default behavior in R for ordered factors is to treat them as equidistant scores and then estimate an orthogonal polynomial function. So the letters L, Q, and C above refer to linear, quadratic, and cubic terms. This default behavior was inherited from S and I would argue that it is … not optimal. First, It is problematic to treat ordinal variables as equidistant scores without letting the researcher make that decision explicitly. Second, the parameter estimates from this approach are completely uninterpretable.</p>
<p>Luckily, it is not difficult to re-specify the contrasts for the education variable. R even provides some handy-dandy functions for common contrasts. In this case, we could re-code back to a standard dummy/indicator variable contrasts with <code>contr.treatment</code>, like so:</p>
<pre class="r"><code>contrasts(earnings$educ_ordered) &lt;- contr.treatment(5)
model_ordinal2 &lt;- lm(wages~educ_ordered, data=earnings)
knitr::kable(round(coef(model_ordinal2), 2), col.names=&quot;coefficients&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">14.26</td>
</tr>
<tr class="even">
<td>educ_ordered2</td>
<td align="right">4.41</td>
</tr>
<tr class="odd">
<td>educ_ordered3</td>
<td align="right">7.65</td>
</tr>
<tr class="even">
<td>educ_ordered4</td>
<td align="right">16.50</td>
</tr>
<tr class="odd">
<td>educ_ordered5</td>
<td align="right">23.91</td>
</tr>
</tbody>
</table>
</div>
<div id="use-the-stairstep-contrast-tell-a-friend" class="section level2">
<h2>Use the stairstep contrast, tell a friend</h2>
<p>However, since we have to re-specify our contrasts, why not take the time to think about better options? The standard dummy variable coding for ordinal variables is often not very informative. For example, I can see that individuals with a graduate degree make $23.91 more per hour than those with no high school diploma. That is a large difference, but I would have expected a large number here given that we are contrasting the poles of the distribution. A far more interesting question is how much more do those with graduate degrees make than those with only a bachelor’s degree? In that case, we are comparing how much the predicted value of the dependent variable changes when you move to the next highest adjacent category.</p>
<p>We can do this for all adjacent pairs by applying a <code>diff</code> to the vector of mean wages:</p>
<pre class="r"><code>diff(wage_means)</code></pre>
<pre><code>##       HS Diploma        AA Degree Bachelors Degree  Graduate Degree 
##         4.407462         3.242862         8.848246         7.410229</code></pre>
<p>Every number gives us the increase in mean hourly wages when you move to that education level from the immediately preceding educational level. The biggest jump is between a Bachelor’s degree and an AA degree, while the smallest jump is between a high school diploma and an AA degree.</p>
<p>I can of course calculate these differences by hand from the results of my dummy variable coding. For example, by taking <span class="math inline">\(23.91-16.50\)</span>, I will be able to see that the increase in expected hourly wages from a Bachelor’s degree to a Graduate degree is 7.41. However, wouldn’t it be nice if there was a contrast coding that would do this for me? It turns out there is!</p>
<p>The contrast coding we want looks like a stairstep.</p>
<pre class="r"><code>cont &lt;- matrix(0, 5, 4)
cont[col(cont)&lt;row(cont)] &lt;- 1
rownames(cont) &lt;- c(&quot;LHS&quot;,&quot;HS&quot;,&quot;AA&quot;,&quot;BA&quot;,&quot;Grad&quot;)
colnames(cont) &lt;- c(&quot;HS vs LHS&quot;, &quot;AA vs HS&quot;, &quot;BA vs AA&quot;, &quot;Grad vs BA&quot;)
cont</code></pre>
<pre><code>##      HS vs LHS AA vs HS BA vs AA Grad vs BA
## LHS          0        0        0          0
## HS           1        0        0          0
## AA           1        1        0          0
## BA           1        1        1          0
## Grad         1        1        1          1</code></pre>
<p>In this coding, each category gets a one if it is at or higher than the critical cut point for that contrast. The idea is that every category gets the effect of making that “jump” if they are at that level or higher. The result looks like a stairstep descending to the left. For this reason, I often call this approach <em>stairstep coding</em>.</p>
<p>Lets try out this stairstep contrast on education:</p>
<pre class="r"><code>contrasts(earnings$educ_ordered) &lt;- cont
model_ordinal3 &lt;- lm(wages~educ_ordered, data=earnings)
knitr::kable(round(coef(model_ordinal3), 2), col.names=&quot;coefficients&quot;) </code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">14.26</td>
</tr>
<tr class="even">
<td>educ_orderedHS vs LHS</td>
<td align="right">4.41</td>
</tr>
<tr class="odd">
<td>educ_orderedAA vs HS</td>
<td align="right">3.24</td>
</tr>
<tr class="even">
<td>educ_orderedBA vs AA</td>
<td align="right">8.85</td>
</tr>
<tr class="odd">
<td>educ_orderedGrad vs BA</td>
<td align="right">7.41</td>
</tr>
</tbody>
</table>
<p>The contrasts behave exactly as expected. Each parameter estimate gives the mean difference between adjacent pairs of categories on the ordinal variable. We can get the mean differences between any non-adjacent pairs simply by adding up the values of all the intervening pairs. For example, to get the difference between an AA degree and a graduate degree I take the two values for BA vs. AA and Grad vs. AA and add them up for <span class="math inline">\(8.85+7.41=16.26\)</span>.</p>
<p>Finally, since setting up this contrast is a hassle, why not put all of it into a function like a coding <i class="fas  fa-user-ninja "></i>?</p>
<pre class="r"><code>ordered_factor &lt;- function(fact_var) {
  ord_fact &lt;- factor(fact_var, ordered=TRUE)
  categories &lt;- levels(fact_var)
  n_cat &lt;- length(categories)
  cont &lt;- matrix(0, n_cat, n_cat-1)
  cont[col(cont)&lt;row(cont)] &lt;- 1
  rownames(cont) &lt;- categories
  colnames(cont) &lt;- paste(categories[2:n_cat], categories[1:(n_cat-1)],
                          sep=&quot; vs. &quot;)
  contrasts(ord_fact) &lt;- cont
  return(ord_fact)
}</code></pre>
<p>This function take a factor variable as input and returns an ordered factor with stairstep contrasts defined as well as intuitive labels. Now you can just apply this function to any existing factor variables to convert them to ordered factors with stairstep contrasts. Here it is in action.</p>
<pre class="r"><code>earnings$education &lt;- ordered_factor(earnings$education)
contrasts(earnings$education)</code></pre>
<pre><code>##                  HS Diploma vs. No HS Diploma AA Degree vs. HS Diploma
## No HS Diploma                               0                        0
## HS Diploma                                  1                        0
## AA Degree                                   1                        1
## Bachelors Degree                            1                        1
## Graduate Degree                             1                        1
##                  Bachelors Degree vs. AA Degree
## No HS Diploma                                 0
## HS Diploma                                    0
## AA Degree                                     0
## Bachelors Degree                              1
## Graduate Degree                               1
##                  Graduate Degree vs. Bachelors Degree
## No HS Diploma                                       0
## HS Diploma                                          0
## AA Degree                                           0
## Bachelors Degree                                    0
## Graduate Degree                                     1</code></pre>
<pre class="r"><code>model_final &lt;- lm(wages~education, data=earnings)
knitr::kable(coef(model_final, 2), col.names=&quot;coefficients&quot;)</code></pre>
<table>
<thead>
<tr class="header">
<th></th>
<th align="right">coefficients</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td align="right">14.261219</td>
</tr>
<tr class="even">
<td>educationHS Diploma vs. No HS Diploma</td>
<td align="right">4.407462</td>
</tr>
<tr class="odd">
<td>educationAA Degree vs. HS Diploma</td>
<td align="right">3.242862</td>
</tr>
<tr class="even">
<td>educationBachelors Degree vs. AA Degree</td>
<td align="right">8.848246</td>
</tr>
<tr class="odd">
<td>educationGraduate Degree vs. Bachelors Degree</td>
<td align="right">7.410229</td>
</tr>
</tbody>
</table>
</div>
